# Generated by Django 4.2.7 on 2023-11-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Work Id')),
                ('link', models.CharField(max_length=150)),
                ('workType', models.CharField(choices=[('Youtube', 'Youtube'), ('Instagram', 'Instagram'), ('Other', 'Other')], max_length=10)),
            ],
        ),
    ]
