# Generated by Django 4.2.7 on 2023-11-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0002_alter_workmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
