# Generated by Django 4.2.7 on 2023-11-30 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistmodel',
            name='userInstance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artistmodel',
            name='work',
            field=models.ManyToManyField(to='Work.workmodel'),
        ),
    ]
