# Generated by Django 4.2.7 on 2023-11-30 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Artist', '0004_alter_artistmodel_userinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistmodel',
            name='userInstance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
